config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|ba/ do
    devise_for :users, path: 'auth',
                       path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

    resources :blog_posts, param: :slug # Ažurirano
    resources :project_posts, param: :slug # Ažurirano
    get 'pages/about'
    get 'pages/projects'
    get 'pages/blog'
    get 'pages/education_training'
    get 'pages/contact'
    get 'pages/nutrition'
    get 'pages/zdrava-ishrana'
    get 'pages/landing'
    get 'pages/talent_management'

    post 'contact_form/send_email'
    post 'contact_form/send_email_landing'
    post 'contact_form/send_academy_email'

    root 'pages#home'
  end

  # Redirect za root putanju bez specificiranog jezika
  get '/', to: redirect("/#{I18n.default_locale}")
end

app/models/project_post.rb
class ProjectPost < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :linked_project_post, class_name: 'ProjectPost', optional: true

  has_one_attached :main_image
  has_many_attached :secondary_images

  before_save :apply_cloudinary_transformation
  after_initialize :set_default_date_of_post

  def plain_text_description
    # Assuming 'description' is the attribute containing HTML text
    ActionView::Base.full_sanitizer.sanitize(description)
  end

  private

  def set_default_date_of_post
    self.date_of_post ||= Date.today
  end

  def apply_cloudinary_transformation
    # Check if the main_image is attached and apply the transformation
    return unless main_image.attached?

    # Get the image dimensions
    width = main_image.metadata[:width]
    height = main_image.metadata[:height]

    # Check if either width or height exceeds the specified limits
    return unless width && height && (width > 950 || height > 650)

    main_image.variant(
      resize_to_limit: [950, 650],
      quality: 'auto'
    )
  end
end

app/controllers/project_posts_controller.rb
class ProjectPostsController < ApplicationController
  def new
    @post = ProjectPost.new
  end

  def edit
    @post = ProjectPost.friendly.find(params[:slug]) # Promijenjeno da koristi slug
  end

  def show
    @post = ProjectPost.friendly.find(params[:slug])

    # Ako dolazi iz promene jezika (iz menija), proveri povezani post
    return unless params[:change]

    # Ako postoji povezani post (na suprotnom jeziku), preusmeri na njega
    if @post.linked_project_post_id.present?
      linked_post = ProjectPost.find_by(id: @post.linked_project_post_id, locale: I18n.locale.to_s)

      if linked_post
        redirect_to project_post_path(linked_post)
      else
        # Ako povezani post ne postoji na trenutnom jeziku, preusmeri na blog index
        redirect_to pages_projects_path(locale: I18n.locale)
      end
    else
      # Ako nema povezanog posta, preusmeri na blog index
      redirect_to pages_projects_path(locale: I18n.locale)
    end
  end

  def create
    @post = ProjectPost.new(project_post_params)
    if @post.save
      flash[:notice] = 'Project post successfully created.'
      redirect_to project_post_path(@post) # Ovdje će se generisati URL sa slugom
    else
      flash[:alert] = 'Error creating the project post.'
      render 'new'
    end
  end

  def update
    @project_post = ProjectPost.friendly.find(params[:slug])

    if @project_post.update(project_post_params)
      # Ažuriraj povezani post (ako postoji)
      if @project_post.linked_project_post_id.present?
        linked_project_post = ProjectPost.find_by(id: @project_post.linked_project_post_id)

        linked_project_post.update(linked_project_post_id: @project_post.id) if linked_project_post
      end

      flash[:notice] = 'Project post successfully updated.'
      redirect_to project_post_path(@project_post)
    else
      flash[:alert] = 'Error updating the project post.'
      render 'edit'
    end
  end

  def destroy
    @post = ProjectPost.friendly.find(params[:slug]) # Promijenjeno da koristi slug
    if @post.destroy # Uklonjena uzvičnica
      redirect_to pages_projects_path, notice: 'Record deleted successfully.'
    else
      flash[:alert] = 'Failed to delete the record.'
      redirect_to project_post_path(@post)
    end
  end

  private

  def project_post_params
    params_edited = params.require(:project_post).permit(:title, :description, :linked_project_post_id, :locale, :main_image,
                                                         secondary_images: [])

    if params_edited.dig(:secondary_images).reject { |x| x == '' }.blank?
      params_edited.except(:secondary_images)
    else
      params_edited
    end
  end
end

app/views/project_posts/_form.html.erb
<div class="container">
  <h2 class="font-weight-bold text-color-dark text-9 mb-4">
    <%= @post.new_record? ? 'Create new post' : 'Edit post' %>
  </h2>
  <div class="row">
    <div class="col-md-6"> <!-- Title takes 75% width on medium-sized screens and larger -->
      <div class="field mb-4">
        <%= f.label :title %>
        <%= f.text_field :title, required: true, class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-3"> <!-- Date field takes 25% width on medium-sized screens and larger -->
      <div class="field mb-4">
        <%= f.label :date_of_post %>
        <%= f.date_field :date_of_post, class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-3"> <!-- Locale takes 25% width on medium-sized screens and larger -->
      <div class="field mb-4">
        <%= f.label :locale, 'Language' %>
        <%= f.select :locale, [['English', 'en'], ['Bosnian', 'ba']], {}, required: true, class: 'form-control' %>
      </div>
    </div>
    <% if !@post.new_record? %> <!-- Only show this field for editing existing posts -->
      <div class="col-md-4"> <!-- Connected post field takes 25% width on medium-sized screens and larger -->
        <div class="form-group mb-4"> <!-- Add form-group for proper spacing -->
          <%= f.label :linked_project_post_id, 'Connected Post (different language)', class: 'form-label' %> <!-- Add class for label styling -->
          <% opposite_locale = @post.locale == 'en' ? 'ba' : 'en' %>
          <%= f.select :linked_project_post_id, 
          ProjectPost.where(locale: opposite_locale).where.not(id: @post.id).pluck(:title, :id), 
          { include_blank: true }, 
          class: 'form-control' %> <!-- Use standard select -->
        </div>
      </div>
    <% end %>
  </div>
  <div class="field mb-4">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'tinymce form-control' %>
  </div>
  <!-- Main Image Upload -->
  <div class="field mb-4">
    <%= f.label :main_image %>
    <% if @post.main_image.attached? %>
      <%= f.file_field :main_image, class: 'form-control', value: @post.main_image, accept: 'image/png, image/jpeg, image/jpg', onchange: 'validateFileType(this, "mainFileList", "submitBtn")' %>
      <ul id="mainFileList">
        <li><%= File.basename(@post.main_image.filename.to_s) %></li>
      </ul>
    <% else %>
      <%= f.file_field :main_image, class: 'form-control', accept: 'image/png, image/jpeg, image/jpg', onchange: 'validateFileType(this, "mainFileList", "submitBtn")' %>
      <ul id="mainFileList"></ul>
    <% end %>
  </div>
  <!-- Secondary Images Upload -->
  <div class="field mb-4">
    <%= f.label :secondary_images %>
    <% if @post.secondary_images.attached? %>
      <%= f.file_field :secondary_images, class: 'form-control', value: @post.secondary_images, multiple: true, accept: 'image/png, image/jpeg, image/jpg', onchange: 'validateFileType(this, "secondaryFileList", "submitBtn")' %>
      <ul id="secondaryFileList">
        <% @post.secondary_images.each do |image| %>
          <li><%= File.basename(image.filename.to_s) %></li>
        <% end %>
      </ul>
    <% else %>
      <%= f.file_field :secondary_images, class: 'form-control', multiple: true, accept: 'image/png, image/jpeg, image/jpg', onchange: 'validateFileType(this, "secondaryFileList", "submitBtn")' %>
      <ul id="secondaryFileList"></ul>
    <% end %>
  </div>
</div>
<script>
  // Function to validate file types and display the file names in a list with remove button
  function validateFileType(input, listId, submitBtnId) {
    const fileNamesList = document.getElementById(listId);
    const submitBtn = document.getElementById(submitBtnId);

    fileNamesList.innerHTML = ''; // Clear previous file list

    const allowedTypes = ['image/jpeg', 'image/png']; // Add more if needed

    Array.from(input.files).forEach(file => {
      if (!allowedTypes.includes(file.type)) {
        alert('Invalid file type. Please select only image files.');
        input.value = ''; // Clear the file input
        return;
      }

      const listItem = document.createElement('li');
      listItem.textContent = file.name;

      const removeButton = document.createElement('button');
      removeButton.textContent = 'Remove';
      removeButton.type = 'button';
      removeButton.onclick = function() {
        removeFileFromList(file, listItem, input, submitBtn);
      };

      listItem.appendChild(removeButton);
      fileNamesList.appendChild(listItem);
    });
  }

  // Function to remove a file from the list
  function removeFileFromList(file, listItem, input, submitBtn) {
    const newFileList = Array.from(input.files).filter(f => f !== file);

    // Create a new FileList using DataTransfer
    const dataTransfer = new DataTransfer();
    newFileList.forEach(f => {
      dataTransfer.items.add(f);
    });

    // Set the new files to the input
    input.files = dataTransfer.files;

    listItem.remove();

  }
</script>

app/views/project_posts/edit.html.erb
<div class="body">
  <div role="main" class="main">
    <section class="page-header page-header-modern bg-primary custom-page-header">
      <div class="custom-svg-style-1 svg-fill-color-primary position-absolute top-0 left-50pct transform3dx-n50 h-100 z-index-0">
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 1920 400" xml:space="preserve" preserveAspectRatio="none" width="100%" height="100%" data-plugin-float-element-svg="true">
          <circle id="svg_2" r="7.5" cy="539.5" cx="209.5" fill="#FFF" opacity="0.2" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.3, 'transition': true, 'transitionDuration': 1000, 'isInsideSVG': true}"/>
          <circle id="svg_3" r="12" cy="211" cx="268" fill="#FFF" opacity="0.2" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.4, 'transition': true, 'transitionDuration': 2000, 'isInsideSVG': true}"/>
          <circle id="svg_4" r="17" cy="144" cx="1864" fill="#FFF" opacity="0.2" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.6, 'transition': true, 'transitionDuration': 1000, 'isInsideSVG': true}"/>
          <circle id="svg_6" r="28.5" cy="326.74992" cx="327.75073" stroke-miterlimit="10" stroke-width="3" stroke="6CD499" fill="none"/>
          <circle opacity="0.2" stroke="#ffffff" id="svg_8" r="21.5" cy="340.25" cx="90.74976" fill="none" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.3, 'transition': true, 'transitionDuration': 1000, 'isInsideSVG': true}"/>
          <circle stroke="#ffffff" opacity="0.2" id="svg_9" r="14.625" cy="689.625" cx="128.87476" fill="none" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.5, 'transition': true, 'transitionDuration': 2000, 'isInsideSVG': true}"/>
        </svg>
      </div>
      <div class="container position-relative z-index-1 mt-4 h-100">
        <div class="row h-100">
          <div class="col align-self-center">
            <div class="d-block">
              <span class="d-block custom-stroke-text-effect-1 custom-big-text-2 font-weight-bold opacity-2"><%= t("projects.title") %></span>
            </div>
            <div class="d-block">
              <h1 class="text-color-light font-weight-bold positive-ls-3 custom-big-text-1 line-height-1 mb-0"><%= t("projects.title") %></h1>
            </div>
          </div>
        </div>
      </div>
    </section>
    <div class="container py-5 mt-4">
      <div class="row">
        <div class="col">
          <%= form_with(model: @post, local: true, url: project_post_path(@post), method: "patch") do |f| %>
            <%= render "form", f: f %>
            <%= f.submit 'Update Post', class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
    <section class="section section-height-3 bg-color-grey-scale-1 border-0 m-0">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-10 text-md-center text-lg-start mb-4 mb-lg-0">
            <h2 class="text-color-dark font-weight-bold mb-1">Zenos is everything you need to help you run your business!</h2>
            <p class="font-weight-bold positive-ls-3 text-4-5 mb-0">Make An Appointment Today With Our Online Form</p>
          </div>
          <div class="col-lg-2 text-md-center text-lg-end">
            <a href="#" class="btn btn-gradient font-weight-bold btn-px-5 btn-py-3">CONTACT US</a>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>

app/views/project_posts/new.html.erb
<div class="body">
  <div role="main" class="main">
    <section class="page-header page-header-modern bg-primary custom-page-header">
      <div class="custom-svg-style-1 svg-fill-color-primary position-absolute top-0 left-50pct transform3dx-n50 h-100 z-index-0">
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 1920 400" xml:space="preserve" preserveAspectRatio="none" width="100%" height="100%" data-plugin-float-element-svg="true">
          <circle id="svg_2" r="7.5" cy="539.5" cx="209.5" fill="#FFF" opacity="0.2" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.3, 'transition': true, 'transitionDuration': 1000, 'isInsideSVG': true}"/>
          <circle id="svg_3" r="12" cy="211" cx="268" fill="#FFF" opacity="0.2" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.4, 'transition': true, 'transitionDuration': 2000, 'isInsideSVG': true}"/>
          <circle id="svg_4" r="17" cy="144" cx="1864" fill="#FFF" opacity="0.2" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.6, 'transition': true, 'transitionDuration': 1000, 'isInsideSVG': true}"/>
          <circle id="svg_6" r="28.5" cy="326.74992" cx="327.75073" stroke-miterlimit="10" stroke-width="3" stroke="6CD499" fill="none"/>
          <circle opacity="0.2" stroke="#ffffff" id="svg_8" r="21.5" cy="340.25" cx="90.74976" fill="none" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.3, 'transition': true, 'transitionDuration': 1000, 'isInsideSVG': true}"/>
          <circle stroke="#ffffff" opacity="0.2" id="svg_9" r="14.625" cy="689.625" cx="128.87476" fill="none" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.5, 'transition': true, 'transitionDuration': 2000, 'isInsideSVG': true}"/>
        </svg>
      </div>
      <div class="container position-relative z-index-1 mt-4 h-100">
        <div class="row h-100">
          <div class="col align-self-center">
            <div class="d-block">
              <span class="d-block custom-stroke-text-effect-1 custom-big-text-2 font-weight-bold opacity-2"><%= t("projects.title") %></span>
            </div>
            <div class="d-block">
              <h1 class="text-color-light font-weight-bold positive-ls-3 custom-big-text-1 line-height-1 mb-0"><%= t("projects.title") %></h1>
            </div>
          </div>
        </div>
      </div>
    </section>
    <div class="container py-5 mt-4">
      <div class="row">
        <div class="col">
          <%= form_with(model: @post, local: true, url: project_posts_path) do |f| %>
            <%= render "form", f: f %>
            <%= f.submit 'Create Post', class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
    <section class="section section-height-3 bg-color-grey-scale-1 border-0 m-0">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-10 text-md-center text-lg-start mb-4 mb-lg-0">
            <h2 class="text-color-dark font-weight-bold mb-1">Zenos is everything you need to help you run your business!</h2>
            <p class="font-weight-bold positive-ls-3 text-4-5 mb-0">Make An Appointment Today With Our Online Form</p>
          </div>
          <div class="col-lg-2 text-md-center text-lg-end">
            <a href="#" class="btn btn-gradient font-weight-bold btn-px-5 btn-py-3">CONTACT US</a>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>

app/views/project_posts/show.html.erb
<div class="body">
  <div role="main" class="main">
    <section class="page-header page-header-modern bg-primary custom-page-header">
      <div class="custom-svg-style-1 svg-fill-color-primary position-absolute top-0 left-50pct transform3dx-n50 h-100 z-index-0">
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 1920 400" xml:space="preserve" preserveAspectRatio="none" width="100%" height="100%" data-plugin-float-element-svg="true">
          <circle id="svg_2" r="7.5" cy="539.5" cx="209.5" fill="#FFF" opacity="0.2" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.3, 'transition': true, 'transitionDuration': 1000, 'isInsideSVG': true}"/>
          <circle id="svg_3" r="12" cy="211" cx="268" fill="#FFF" opacity="0.2" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.4, 'transition': true, 'transitionDuration': 2000, 'isInsideSVG': true}"/>
          <circle id="svg_4" r="17" cy="144" cx="1864" fill="#FFF" opacity="0.2" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.6, 'transition': true, 'transitionDuration': 1000, 'isInsideSVG': true}"/>
          <circle id="svg_6" r="28.5" cy="326.74992" cx="327.75073" stroke-miterlimit="10" stroke-width="3" stroke="6CD499" fill="none"/>
          <circle opacity="0.2" stroke="#ffffff" id="svg_8" r="21.5" cy="340.25" cx="90.74976" fill="none" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.3, 'transition': true, 'transitionDuration': 1000, 'isInsideSVG': true}"/>
          <circle stroke="#ffffff" opacity="0.2" id="svg_9" r="14.625" cy="689.625" cx="128.87476" fill="none" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.5, 'transition': true, 'transitionDuration': 2000, 'isInsideSVG': true}"/>
        </svg>
      </div>
      <div class="container position-relative z-index-1 mt-4 h-100">
        <div class="row h-100">
          <div class="col align-self-center">
            <div class="d-block">
              <span class="d-block custom-stroke-text-effect-1 custom-big-text-2 font-weight-bold opacity-2"><%= t("projects.title") %></span>
            </div>
            <div class="d-block">
              <h1 class="text-color-light font-weight-bold positive-ls-3 custom-big-text-1 line-height-1 mb-0"><%= t("projects.title") %></h1>
            </div>
          </div>
        </div>
      </div>
    </section>
    <div class="container py-4">
      <div class="row">
        <div class="col">
          <div class="blog-posts single-post">
            <article class="post post-large blog-single-post border-0 m-0 p-0">
              <% if @post.main_image.attached? %>
                <div class="post-image ms-0" style="display: flex; justify-content: center; align-items: center;">
                  <%= cl_image_tag(@post.main_image.key, class: 'img-fluid img-thumbnail img-thumbnail-no-borders rounded shadow post-slika', style: 'max-width: 950px; max-height: 650px; object-fit: cover;', alt: '') %>
                </div>
              <% end %>
              <div class="post-date ms-0">
                <span class="day"><%= @post.created_at.strftime("%d") %></span>
                <span class="month"><%= @post.created_at.strftime("%b") %></span>
              </div>
              <div class="post-content ms-0">
                <div class="d-flex justify-content-between align-items-center">
                  <h2 class="font-weight-semi-bold"><%= @post.title %></h2>
                  <% if user_signed_in? %>
                    <div class="d-flex justify-content-between align-items-center">
                      <!-- Edit Button -->
                      <%= link_to edit_project_post_path(@post), class: "btn btn-primary me-2" do %>
                        Edit
                      <% end %>
                      <%= button_to "Delete", project_post_path(@post), class: "btn btn-danger", data: { confirm: "Are you sure?" }, method: :delete %></p>
                  </div>
                <% end %>
              </div>
              <div class="post-meta">
                <span><i class="fa-solid fa-calendar"></i>Datum: <%= @post.created_at.strftime("%d/%m/%Y") %> </span>
              </div>
              <p><%= @post.description.html_safe %></p>
              <div class="row justify-content-center">
                <div class="col-lg-6">
                  <div class="owl-carousel owl-theme nav-inside" data-plugin-options="{'items': 1, 'margin': 10, 'loop': false, 'nav': true, 'dots': false}">
                    <% @post.secondary_images.each_with_index do |image, index| %>
                      <div>
                        <div class="img-thumbnail border-0 p-0 d-block">
                          <img class="img-fluid border-radius-0" src="<%= image.url %>" alt="">
                        </div>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
              <div class="row justify-content-center">
                <div class="col-lg-6">
                  <div class="image-previews">
                    <% @post.secondary_images.each_with_index do |image, index| %>
                      <div class="image-preview" data-index="<%= index %>">
                        <img src="<%= image.url %>" alt="">
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
              <!--<div class="post-block mt-5 post-share">
                  <h4 class="mb-3">Share this Post</h4>
                   Go to www.addthis.com/dashboard to customize your tools 
                  <div class="addthis_inline_share_toolbox"></div>
                  <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-60ba220dbab331b0"></script>-->
            </div>
          </div>
        </article>
      </div>
    </div>
  </div>
</div>
<%= render "shared/contact_us" %>
</div>
</div>