config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|ba/ do
    devise_for :users, path: 'auth',
                       path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

    resources :blog_posts, param: :slug # Ažurirano
    resources :project_posts, param: :slug # Ažurirano
    get 'pages/about'
    get 'pages/projects'
    get 'pages/blog'
    get 'pages/education_training'
    get 'pages/contact'
    get 'pages/nutrition'
    get 'pages/zdrava-ishrana'
    get 'pages/landing'
    get 'pages/talent_management'

    post 'contact_form/send_email'
    post 'contact_form/send_email_landing'
    post 'contact_form/send_academy_email'

    root 'pages#home'
  end

  # Redirect za root putanju bez specificiranog jezika
  get '/', to: redirect("/#{I18n.default_locale}")
end

app/views/shared/_contact_us.html.erb
<section class="section section-height-3 bg-color-grey-scale-1 border-0 m-0">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-10 text-md-center text-lg-start mb-4 mb-lg-0">
        <h2 class="text-color-dark font-weight-bold mb-1 text-justify"><%= t("shared.contact.moto") %></h2>
        <p class="font-weight-bold positive-ls-3 text-4-5 mb-0 text-justify"><%= t("shared.contact.get_in") %></p>
      </div>
      <div class="contact-us col-lg-2 text-md-center text-lg-end">
        <%= link_to t("shared.contact.contact_us"), pages_contact_path, class: "btn btn-gradient font-weight-bold btn-px-5 btn-py-3" %>
      </div>
    </div>
  </div>
</section>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show position-fixed top-0 start-50 translate-middle-x m-2" role="alert" style="width: 500px; height: 100px; margin-top: 350px !important">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <script>
      setTimeout(function() {
        $('.alert').alert('close');
      }, 3000);
    </script>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <script>
      setTimeout(function() {
        $('.alert').alert('close');
      }, 3000);
    </script>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="footer" class="footer-top-border mt-0 bg-color-light-scale-1">
  <div class="footer-copyright bg-color-light-scale-1 container">
      <div class="row footer-row">
        <div class="col-md-4 d-flex align-items-center justify-content-center copyright">
          <p><strong>ZENOS</strong> - © Copyright 2023 - All Rights Reserved.</p>
        </div>
        <div class="col-md-8 d-flex align-items-center justify-content-center contact">
          <p class="contact-info"><a href="tel:+387 62 268 198">+387 62 268 198</a> | <a href="mailto:info@zen-os.com" target="_blank">info@zen-os.com</a> | Zmaja od Bosne bb (Poslovna zona Zenica I), Zenica</p>
          <ul class="footer-social-icons social-icons social-icons-clean social-icons-icon-dark social-icons-big ms-3">
            <li class="social-icons-instagram"><a href="https://www.instagram.com/zenos.education/" target="_blank" title="Intagram"><i class="fab fa-instagram text-4"></i></a></li>
            <li class="social-icons-facebook"><a href="https://www.facebook.com/zenos.2019" target="_blank" title="Facebook"><i class="fab fa-facebook-f text-4"></i></a></li>
            <li class="social-icons-linkedin"><a href="https://www.linkedin.com/company/zen-os/" target="_blank" title="Linkedin"><i class="fab fa-linkedin-in"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
</footer>

app/views/shared/_navbar.html.erb
<header id="header" class="header-transparent header-effect-shrink" data-plugin-options="{'stickyEnabled': true, 'stickyEffect': 'shrink', 'stickyEnableOnBoxed': true, 'stickyEnableOnMobile': false, 'stickyChangeLogo': false, 'stickyStartAt': 30, 'stickyHeaderContainerHeight': 100}">
  <div class="header-body border-top-0 bg-primary box-shadow-none">
    <div class="header-container container">
      <div class="header-row">
        <div class="header-column">
          <div class="header-row">
            <div class="header-logo">
              <%= link_to root_path, class: "nav-link" do %>
                <%= image_tag('Zenos_logo_web_bijela.png', alt: 'zenos', class: 'logo') %>
              <% end %>
            </div>
            <!-- Dodajemo ovu verziju jezičkih linkova na mobilnim uređajima -->
          </div>
        </div>
        <div class="header-column justify-content-end">
          <div class="header-row">
            <div class="language-switcher-mob d-lg-none">
              <%= link_to("EN", url_for(locale: 'en', change: true), class: "nav-link") %>
              <span class="language-separator">|</span>
              <%= link_to("BA", url_for(locale: 'ba', change: true), class: "nav-link") %>
            </div>
            <div class="header-nav header-nav-links header-nav-line header-nav-bottom-line header-nav-bottom-line-active-text-light header-nav-dropdowns-dark header-nav-light-text">
              <div class="header-nav-main header-nav-main-text-capitalize header-nav-main-mobile-dark header-nav-main-square header-nav-main-dropdown-no-borders header-nav-main-effect-2 header-nav-main-sub-effect-1">
                <nav class="collapse">
                  <ul class="nav nav-pills no-text-transform" id="mainNav">
                    <li>
                      <%= link_to t("shared.navbar.home"), root_path, class: "nav-link padding-mob-nav-li" %>
                    </li>
                    <li>
                      <%= link_to t("shared.navbar.about"), pages_about_path, class: "nav-link padding-mob-nav-li" %>
                    </li>
                    <li>
                      <%= link_to t("shared.navbar.projects"), pages_projects_path, class: "nav-link padding-mob-nav-li" %>
                    </li>
                    <li>
                      <%= link_to t("shared.navbar.blog"), pages_blog_path, class: "nav-link padding-mob-nav-li" %>
                    </li>
                    <li>
                      <%= link_to t("shared.navbar.education_training"), pages_education_training_path, class: "nav-link padding-mob-nav-li" %>
                    </li>
                    <li>
                      <%= link_to t("shared.navbar.contact"), pages_contact_path, class: "nav-link padding-mob-nav-li" %>
                    </li>
                    <li>
                      <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link padding-mob-nav-li" if user_signed_in? %>
                    </li>
                  </ul>
                </nav>
              </div>
            </div>
            <button class="btn header-btn-collapse-nav ms-3 ms-sm-4" data-bs-toggle="collapse" data-bs-target=".header-nav-main nav">
              <i class="fas fa-bars"></i>
            </button>
          </div>
        </div>
      </div>
    </div>
    <!-- Dodajemo ovaj div za jezičke linkove -->
    <div class="language-switcher d-none d-lg-flex align-items-center">
      <%= link_to("EN", url_for(locale: 'en', change: true), class: "nav-link margin-0") %>
      <span class="language-separator">|</span>
      <%= link_to("BA", url_for(locale: 'ba', change: true), class: "nav-link margin-0") %>
    </div>
  </div>
</div>
</header>