config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|ba/ do
    devise_for :users, path: 'auth',
                       path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

    resources :blog_posts, param: :slug # Ažurirano
    resources :project_posts, param: :slug # Ažurirano
    get 'pages/about'
    get 'pages/projects'
    get 'pages/blog'
    get 'pages/education_training'
    get 'pages/contact'
    get 'pages/nutrition'
    get 'pages/zdrava-ishrana'
    get 'pages/landing'
    get 'pages/talent_management'

    post 'contact_form/send_email'
    post 'contact_form/send_email_landing'
    post 'contact_form/send_academy_email'

    root 'pages#home'
  end

  # Redirect za root putanju bez specificiranog jezika
  get '/', to: redirect("/#{I18n.default_locale}")
end

app/views/pages/_card.html.erb
<div class="col-md-4 card-blog">
  <article class="post post-medium border-0 pb-0 mb-5 rounded shadow-with-padding">
    <div class="post-image">
      <%= link_to post.is_a?(BlogPost) ? blog_post_path(post) : project_post_path(post) do %>
        <%= cl_image_tag(post.main_image.key, alt: 'Main Image', class: 'img-fluid rounded', style: 'width: 100%; object-fit: cover; height: 100%;', width: 700, height: 600, crop: :fill) if post.main_image.attached? %>
      <% end %>
    </div>
    <div class="post-content p-4">
      <div class="post-date">
        <span class="day"><%= post.date_of_post.strftime("%d") %></span>
        <span class="month"><%= post.date_of_post.strftime("%b") %></span>
        <span class="year"><%= post.date_of_post.strftime("%Y") %></span>
      </div>
      <h4><%= link_to truncate(post.title, length: 55), post.is_a?(BlogPost) ? blog_post_path(post) : project_post_path(post), class: "text-decoration-none text-2" %></h4>
      <p class="mb-1"><%= truncate(post.plain_text_description, length: 250) %></p>
      <div class="d-flex justify-content-end">
        <%= link_to  post.is_a?(BlogPost) ? blog_post_path(post) : project_post_path(post), class: 'btn btn-primary btn-sm text-2' do %>
          Read More <i class="fas fa-chevron-right text-1 ms-1"></i>
        <% end %>
      </div>
    </div>
  </article>
</div>

app/views/pages/blog.html.erb
<div class="body">
  <div role="main" class="main">
    <section class="page-header page-header-modern bg-primary custom-page-header">
      <div class="custom-svg-style-1 svg-fill-color-primary position-absolute top-0 left-50pct transform3dx-n50 h-100 z-index-0">
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 1920 400" xml:space="preserve" preserveAspectRatio="none" width="100%" height="100%" data-plugin-float-element-svg="true">
          <circle id="svg_2" r="7.5" cy="539.5" cx="209.5" fill="#FFF" opacity="0.2" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.3, 'transition': true, 'transitionDuration': 1000, 'isInsideSVG': true}"/>
          <circle id="svg_3" r="12" cy="211" cx="268" fill="#FFF" opacity="0.2" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.4, 'transition': true, 'transitionDuration': 2000, 'isInsideSVG': true}"/>
          <circle id="svg_4" r="17" cy="144" cx="1864" fill="#FFF" opacity="0.2" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.6, 'transition': true, 'transitionDuration': 1000, 'isInsideSVG': true}"/>
          <circle id="svg_6" r="28.5" cy="326.74992" cx="327.75073" stroke-miterlimit="10" stroke-width="3" stroke="6CD499" fill="none"/>
          <circle opacity="0.2" stroke="#ffffff" id="svg_8" r="21.5" cy="340.25" cx="90.74976" fill="none" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.3, 'transition': true, 'transitionDuration': 1000, 'isInsideSVG': true}"/>
          <circle stroke="#ffffff" opacity="0.2" id="svg_9" r="14.625" cy="689.625" cx="128.87476" fill="none" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.5, 'transition': true, 'transitionDuration': 2000, 'isInsideSVG': true}"/>
        </svg>
      </div>
      <div class="container position-relative z-index-1 mt-4 h-100">
        <div class="row h-100">
          <div class="col align-self-center font-span">
            <div class="d-block">
              <span class="d-block custom-stroke-text-effect-1 custom-big-text-2 font-weight-bold opacity-2"><%= t("blog.title") %></span>
            </div>
            <div class="d-block">
              <h1 class="text-color-light font-weight-bold positive-ls-3 custom-big-text-1 line-height-1 mb-0"><%= t("blog.title") %></h1>
            </div>
          </div>
        </div>
      </div>
    </section>
    <div class="container py-5 mt-4">
      <div class="row">
        <div class="col">
          <div class="d-flex justify-content-between align-items-center mb-4">
            <h2 class="font-weight-bold text-color-dark text-9 mb-4"><%= t("blog.title") %></h2>
            <% if user_signed_in? %>
              <div class="col-lg-2 text-md-center text-lg-end">
                <%= link_to t("projects.create"), new_blog_post_path, class: 'btn btn-lg btn-primary font-weight-bold' %>
              </div>
            <% end %>
          </div>
          <p class="text-4-5 line-height-7 text-justify"><%= t("blog.description") %></p>
          <div class="container py-4">
            <div class="row">
              <div class="col">
                <div class="blog-posts">
                  <% @posts.each_slice(3) do |post_group| %>
                    <div class="row">
                      <% post_group.each do |post| %>
                        <%= render 'pages/card', post: post %>
                      <% end %>
                    </div>
                  <% end %>
                  <!-- 
                <div class="row">
                  <div class="col">
                    <ul class="pagination float-end">
                      <li class="page-item"><a class="page-link" href="#"><i class="fas fa-angle-left"></i></a></li>
                      <li class="page-item active"><a class="page-link" href="#">1</a></li>
                      <li class="page-item"><a class="page-link" href="#">2</a></li>
                      <li class="page-item"><a class="page-link" href="#">3</a></li>
                      <li class="page-item"><a class="page-link" href="#"><i class="fas fa-angle-right"></i></a></li>
                    </ul>
                  </div>
                </div> -->
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%= render "shared/contact_us" %>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="body">
  <div role="main" class="main">
    <section class="page-header page-header-modern bg-primary custom-page-header mb-0">
      <div class="custom-svg-style-1 svg-fill-color-primary position-absolute top-0 left-50pct transform3dx-n50 h-100 z-index-0">
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 1920 400" xml:space="preserve" preserveAspectRatio="none" width="100%" height="100%" data-plugin-float-element-svg="true">
          <circle id="svg_2" r="7.5" cy="539.5" cx="209.5" fill="#FFF" opacity="0.2" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.3, 'transition': true, 'transitionDuration': 1000, 'isInsideSVG': true}"/>
          <circle id="svg_3" r="12" cy="211" cx="268" fill="#FFF" opacity="0.2" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.4, 'transition': true, 'transitionDuration': 2000, 'isInsideSVG': true}"/>
          <circle id="svg_4" r="17" cy="144" cx="1864" fill="#FFF" opacity="0.2" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.6, 'transition': true, 'transitionDuration': 1000, 'isInsideSVG': true}"/>
          <circle id="svg_6" r="28.5" cy="326.74992" cx="327.75073" stroke-miterlimit="10" stroke-width="3" stroke="6CD499" fill="none"/>
          <circle opacity="0.2" stroke="#ffffff" id="svg_8" r="21.5" cy="340.25" cx="90.74976" fill="none" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.3, 'transition': true, 'transitionDuration': 1000, 'isInsideSVG': true}"/>
          <circle stroke="#ffffff" opacity="0.2" id="svg_9" r="14.625" cy="689.625" cx="128.87476" fill="none" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.5, 'transition': true, 'transitionDuration': 2000, 'isInsideSVG': true}"/>
        </svg>
      </div>
      <div class="container position-relative z-index-1 mt-4 h-100">
        <div class="row h-100">
          <div class="col align-self-center font-span">
            <div class="d-block">
              <span class="d-block custom-stroke-text-effect-1 custom-big-text-2 font-weight-bold opacity-2"><%= t("contact.title") %></span>
            </div>
            <div class="d-block">
              <h1 class="text-color-light font-weight-bold positive-ls-3 custom-big-text-1 line-height-1 mb-0"><%= t("contact.title") %></h1>
            </div>
          </div>
        </div>
      </div>
    </section>
    <div class="container py-5 mt-4 send-message-container">
      <div class="row">
        <div class="col-md-6">
          <div class="container py-5 my-4">
            <div class="row">
              <div class="col">
                <h2 class="font-weight-bold text-color-dark text-7 mt-0 mb-4"><%= t("contact.form.title") %></h2>
                <%= form_with(url: contact_form_send_email_path, method: 'post', local: true, class: 'contact-form custom-form-style-1', id: 'contact-form') do |form| %>
                  <div class="contact-form-success alert alert-success d-none mt-4">
                    <strong>Success!</strong> Your message has been sent to us.
                  </div>
                  <div class="contact-form-error alert alert-danger d-none mt-4">
                    <strong>Error!</strong> There was an error sending your message.
                    <span class="mail-error-message text-1 d-block"></span>
                  </div>
                  <div class="row row-gutter-sm">
                    <div class="form-group col-lg-6 mb-4">
                      <%= form.text_field :name, class: 'form-control', id: 'name', required: true, placeholder: t("contact.form.name"), maxlength: 100, 'data-msg-required' => t("contact.form.name_error") %>
                    </div>
                    <div class="form-group col-lg-6 mb-4">
                      <%= form.text_field :phone, class: 'form-control', id: 'phone', required: true, placeholder: t("contact.form.phone"), maxlength: 100, 'data-msg-required' => t("contact.form.phone_error") %>
                    </div>
                  </div>
                  <div class="row row-gutter-sm">
                    <div class="form-group col-lg-6 mb-4">
                      <%= form.email_field :email, class: 'form-control', id: 'email', required: true, placeholder: t("contact.form.email"), maxlength: 100, 'data-msg-required' => 'Please enter your email address.', 'data-msg-email' => t("contact.form.email_error") %>
                    </div>
                    <div class="form-group col-lg-6 mb-4">
                      <%= form.text_field :subject, class: 'form-control', id: 'subject', required: true, placeholder: t("contact.form.subject"), maxlength: 100, 'data-msg-required' => t("contact.form.subject_error") %>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group col mb-4">
                      <%= form.text_area :message, class: 'form-control', id: 'message', required: true, placeholder: t("contact.form.message"), maxlength: 5000, 'data-msg-required' => t("contact.form.message_error"), rows: 10 %>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group col mb-3 send-message">
                      <%= form.submit t("contact.form.send_message"), class: 'btn btn-gradient font-weight-bold btn-px-5 btn-py-3' %>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="800">
            <h4 class="text-primary pt-5rem"><%= t("contact.address.title") %></h4>
            <ul class="list list-icons list-icons-style-3 mt-2">
              <li><i class="fas fa-map-marker-alt top-6"></i> <strong><%= t("contact.address.address") %></strong> Zmaja od Bosne bb (Poslovna zona Zenica I), 72000 Zenica Bosnia and Herzegovina</li>
              <li><i class="fas fa-phone top-6"></i> <strong><%= t("contact.address.phone") %></strong>+387 62 268 198</li>
              <li><i class="fas fa-envelope top-6"></i> <strong><%= t("contact.address.email") %></strong> <a href="mailto:info@zen-os.com" target="_blank" class="text-decoration-none">info@zen-os.com</a></li>
            </ul>
            <h4 class="text-primary pt-5"><%= t("contact.address.working_hours.title") %></h4>
            <ul class="list list-icons list-dark mt-2">
              <li><i class="far fa-clock top-6"></i><%= t("contact.address.working_hours.monday_friday") %></li>
              <li><i class="far fa-clock top-6"></i><%= t("contact.address.working_hours.weekend") %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="body">
  <div role="main" class="main">
    <div class="owl-carousel owl-carousel-light owl-carousel-light-init-fadeIn owl-theme manual dots-inside dots-horizontal-center custom-dots-style-1 dots-light show-dots-hover show-dots-xs show-dots-sm show-dots-md nav-style-1 nav-inside nav-inside-plus nav-light nav-lg nav-font-size-lg show-nav-hover bg-color-quaternary custom-slider-container mb-0" data-plugin-options="{'autoplay': false, 'autoplayTimeout': 7000}" data-dynamic-height="['780px','780px','780px','780px','510px']" style="height: 780px;">
      <div class="owl-stage-outer">
        <div class="owl-stage">
          <!-- Carousel Slide 1 -->
          <div class="owl-item position-relative overflow-hidden">
            <%= image_tag('enaema2.jpg', class: 'custom-bg-slider-right', alt: '') %>
            <div class="custom-svg-style-1 svg-fill-color-primary position-absolute top-0 left-50pct transform3dx-n50 h-100 z-index-0">
              <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 1920 799" xml:space="preserve" preserveAspectRatio="none" width="100%" height="100%" data-plugin-float-element-svg="true">
                <path id="svg_1" d="m803,799c-0.65,-17.51 -0.69,-41.58 2,-70c7.66,-80.82 31.97,-139.52 47,-175c30.86,-72.87 67.88,-124.83 89,-152c17.86,-22.98 84.33,-105.42 201,-174c34.75,-20.42 121.02,-67.28 243,-90c48.07,-8.95 141.2,-21.52 256,-4c123.54,18.85 208.91,62.88 228,73c21.42,11.35 38.74,22.03 51,30c0,-79 0,-158 0,-237c-640,0 -1280,0 -1920,0c0,266.33 0,532.67 0,799c267.67,0 535.33,0 803,0z" fill="#48C97F"/>
                <circle id="svg_2" r="7.5" cy="539.5" cx="209.5" fill="#FFF" opacity="0.2" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.3, 'transition': true, 'transitionDuration': 1000, 'isInsideSVG': true}"/>
                <circle id="svg_3" r="12" cy="211" cx="268" fill="#FFF" opacity="0.2" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.4, 'transition': true, 'transitionDuration': 2000, 'isInsideSVG': true}"/>
                <circle id="svg_4" r="17" cy="144" cx="1864" fill="#FFF" opacity="0.2" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.6, 'transition': true, 'transitionDuration': 1000, 'isInsideSVG': true}"/>
                <path id="svg_5" d="m982,356c24.33,-22.33 48.67,-44.67 73,-67c-1.91,-2.73 -5.1,-6.6 -10,-10c-7.11,-4.93 -13.93,-6.15 -19,-7c-5.42,-0.91 -14.32,-2.3 -25,1c-4.46,1.38 -16.54,5.83 -25,18c-5.85,8.41 -7.29,16.65 -8,21c-0.51,3.13 -1.54,9.79 0,18c2.48,13.19 10.04,22.01 14,26z" fill="#FFF" opacity="0.2" style="fill: #FFF !important;"/>
                <circle id="svg_6" r="28.5" cy="326.74992" cx="327.75073" stroke-miterlimit="10" stroke-width="3" stroke="6CD499" fill="none"/>
                <circle opacity="0.2" stroke="#ffffff" id="svg_8" r="21.5" cy="340.25" cx="90.74976" fill="none" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.3, 'transition': true, 'transitionDuration': 1000, 'isInsideSVG': true}"/>
                <circle stroke="#ffffff" opacity="0.2" id="svg_9" r="14.625" cy="689.625" cx="128.87476" fill="none" data-plugin-float-element data-plugin-options="{'startPos': 'top', 'speed': 0.5, 'transition': true, 'transitionDuration': 2000, 'isInsideSVG': true}"/>
              </svg>
            </div>
            <div class="container position-relative h-100 z-index-1 mt-4">
              <div class="row titles align-items-center h-100">
                <div class="col mb-5-5 mb-sm-0 font-span phone-titles">
                  <div class="zenos-titles">
                    <div class="appear-animation" data-appear-animation="fadeInDownShorterPlus" data-appear-animation-delay="400">
                      <span class="d-block custom-stroke-text-effect-1 custom-big-text-2 font-weight-bold opacity-2">ZENOS</span>
                    </div>
                    <div class="appear-animation" data-appear-animation="fadeInDownShorterPlus" data-appear-animation-delay="600">
                      <span class="d-block custom-stroke-text-effect-1 custom-big-text-2 font-weight-bold opacity-5">ZENOS</span>
                    </div>
                    <div class="appear-animation" data-appear-animation="fadeInDownShorterPlus" data-appear-animation-delay="800">
                      <span class="d-block custom-stroke-text-effect-1 custom-big-text-2 font-weight-bold">ZENOS</span>
                    </div>
                    <div class="appear-animation" data-appear-animation="fadeInDownShorterPlus" data-appear-animation-delay="1000">
                      <h1 class="text-color-light font-weight-bold positive-ls-3 custom-big-text-1 line-height-1 mb-0">ZENOS</h1>
                    </div>
                  </div>
                  <p class="text-color-dark font-weight-bold text-7 text-sm-9 ms-2 mb-0 appear-animation custom-text-moto-1" data-appear-animation="fadeInDownShorterPlus" data-appear-animation-delay="1200">Your reliable partner</p>
                  <p class="text-color-dark font-weight-bold text-7 text-sm-9 ms-2 mb-0 appear-animation mt-3 custom-text-moto-2" data-appear-animation="fadeInDownShorterPlus" data-appear-animation-delay="1400">in driving the change!</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container py-5 my-4">
      <div class="row">
        <% data = {
						'economic_empowerment.svg': 'economic',
						'bullhorn-solid.svg': 'marketing',
						'book-solid.svg': 'education',
						'people-group-solid.svg': 'inclusion',
						'mountain-city-solid.svg': 'social',
						'cultural_intelligence.svg': 'cultural',
						'apple-whole-solid.svg': 'healty',
						'lightbulb-solid.svg': 'entreprenurship'
					} %>
        <% data.each do |path, name| %>
          <div class="col-md-3">
            <div class="featured-boxes featured-boxes-style-6 p-0 m-0">
              <div class="featured-box featured-box-primary featured-box-effect-6 p-0 m-0">
                <div class="box-content p-0 m-0 text-center">
                  <%= image_tag(path, width: 70, height: 70, alt: '', data: { icon: true, plugin_options: { onlySVG: true, extraClass: 'svg-fill-color-primary px-5 py-4' } }) %>
                  <h4 class="positive-ls-3 font-weight-bold text-3"><%= t("home.cards.#{name}") %></h4>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <section class="section section-height-3 bg-dark border-0 m-0 appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="200">
      <Div class="container">
        <div class="row">
          <div class="col text-center">
            <h2 class="text-color-light font-weight-bold text-9 mb-4 appear-animation" data-appear-animation="fadeInUpShorterPlus" data-appear-animation-delay="600"><%= t("home.who.title") %></h2>
          </div>
        </div>
        <div class="row justify-content-center appear-animation" data-appear-animation="fadeInUpShorterPlus" data-appear-animation-delay="800">
          <div class="col-lg-10">
            <div class="owl-carousel owl-theme nav-bottom rounded-nav dots-light custom-dots-style-1 mb-0" data-plugin-options="{'items': 1, 'loop': false}">
              <div>
                <div class="testimonial testimonial-style-2 testimonial-with-quotes testimonial-remove-right-quote testimonial-light mb-4">
                  <p class="text-color-light opacity-7 text-5 line-height-5 mb-5"><%= t("home.who.first_part") %></p>
                  <p class="text-color-light opacity-7 text-5 line-height-5 mb-5"><%= t("home.who.second_part") %></p>
                  <p class="text-color-light opacity-7 text-5 line-height-5 mb-0"><%= t("home.who.third_part") %></p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </Div>
    </section>
    <div class="container py-5 my-4">
      <div class="row">
        <div class="col">
          <div class="text-center">
            <div class="testimonial testimonial-style-2 testimonial-with-quotes testimonial-quotes-dark mb-0">
              <blockquote>
                <p class="mb-0 custom-font-1 fst-italic text-5 line-height-7"><%= t("home.qoute.text") %></p>
              </blockquote>
              <div class="testimonial-author">
                <p><strong class="font-weight-bold text-color-secondary"><%= t("home.qoute.signature") %></strong></p>
              </div>
            </div>
            <%= image_tag('ZENOS-transparent-13.png',class: 'img-fluid', alt: 'signature', width: 135) %>
          </div>
        </div>
      </div>
    </div>
    <%= render "shared/contact_us" %>
  </div>
</div>
<div class="modal fade" id="countdownmodalpromjeniakobudeshtioopet" tabindex="-1" role="dialog" aria-labelledby="talentModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content p-4">

      <!-- Close button u svom divu, apsolutno pozicioniran -->
      <div class="position-absolute" style="top: 15px; right: 20px; z-index: 1051;">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
        </button>
      </div>

      <!-- Naslov posebno centriran -->
      <div class="modal-header border-0 justify-content-center">
        <h4 class="modal-title font-weight-bold text-5 text-center w-100 mb-0" id="talentModalLabel">
          <%= t("home.talent_modal.title") %>
        </h4>
      </div>

      <div class="modal-body text-center pb-0">
        <p class="text-4 mb-3"><%= t("home.talent_modal.subtitle") %></p>
        <p class="mb-4 text-4"><%= t("home.talent_modal.countdown_intro") %></h5>

        <!-- Countdown -->
        <div id="custom-countdown" class="d-flex justify-content-center gap-4 flex-wrap mb-4">
          <% %w[days hours minutes seconds].each do |unit| %>
            <div class="text-center">
              <span class="p font-weight-bold text-8 text-color-primary d-block" id="cd-<%= unit %>">00</span>
              <small class="p text-muted text-3 text-uppercase"><%= t("home.talent_modal.units.#{unit}") %></small>
            </div>
          <% end %>
        </div>

       <%= link_to t("home.talent_modal.cta_button"), pages_talent_management_path(locale: I18n.locale), class: "btn btn-primary btn-modern text-uppercase font-weight-bold px-5 py-3 mt-3" %>

      </div>
    </div>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function () {
  // Modal trigger
  $('#talentModal').modal('show');

  // Countdown logic
  const deadline = new Date("2025-08-31T23:59:59").getTime();

  function updateCountdown() {
    const now = new Date().getTime();
    const diff = deadline - now;

    const days = Math.floor(diff / (1000 * 60 * 60 * 24));
    const hours = Math.floor((diff / (1000 * 60 * 60)) % 24);
    const minutes = Math.floor((diff / (1000 * 60)) % 60);
    const seconds = Math.floor((diff / 1000) % 60);

    document.getElementById("cd-days").textContent = days;
    document.getElementById("cd-hours").textContent = hours.toString().padStart(2, '0');
    document.getElementById("cd-minutes").textContent = minutes.toString().padStart(2, '0');
    document.getElementById("cd-seconds").textContent = seconds.toString().padStart(2, '0');
  }

  updateCountdown();
  setInterval(updateCountdown, 1000);
});
</script>